{
    "id": 135513,
    "name": "CVE-2019-19950",
    "cwe": "CWE-416",
    "modified": "2022-10-31T13:50:24",
    "published": "2019-12-24T00:15:11",
    "status": "Analyzed",
    "summary": "In GraphicsMagick 1.4 snapshot-20190403 Q8, there is a use-after-free in ThrowException and ThrowLoggedException of magick/error.c.",
    "cvss3": {
        "cvss": 9.8,
        "exploitability_score": 3.9,
        "impact_score": 5.9,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 6.4,
        "cvss": 7.5,
        "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
    },
    "cpes": [
        {
            "id": 109409
        },
        {
            "id": 124875
        },
        {
            "id": 252804
        },
        {
            "id": 463811
        },
        {
            "id": 587080
        },
        {
            "id": 820854
        }
    ]
}