{
    "id": 223165,
    "name": "CVE-2021-46179",
    "cwe": "CWE-617",
    "modified": "2023-08-25T17:52:59",
    "published": "2023-08-22T17:16:21",
    "status": "Analyzed",
    "summary": "Reachable Assertion vulnerability in upx before 4.0.0 allows attackers to cause a denial of service via crafted file passed to the the readx function.",
    "cvss3": {
        "cvss": 6.5,
        "exploitability_score": 2.8,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    },
    "cvss2": null,
    "cpes": [
        {
            "id": 402918
        },
        {
            "id": 402919
        },
        {
            "id": 402920
        },
        {
            "id": 402921
        },
        {
            "id": 402922
        },
        {
            "id": 402923
        },
        {
            "id": 402924
        },
        {
            "id": 402925
        },
        {
            "id": 402926
        },
        {
            "id": 402927
        },
        {
            "id": 402928
        },
        {
            "id": 402929
        },
        {
            "id": 402930
        },
        {
            "id": 402931
        },
        {
            "id": 402932
        },
        {
            "id": 402933
        },
        {
            "id": 402934
        },
        {
            "id": 402935
        },
        {
            "id": 402936
        },
        {
            "id": 402937
        },
        {
            "id": 402938
        },
        {
            "id": 402939
        },
        {
            "id": 402940
        },
        {
            "id": 402941
        },
        {
            "id": 402942
        },
        {
            "id": 402943
        },
        {
            "id": 402944
        },
        {
            "id": 402945
        },
        {
            "id": 402946
        },
        {
            "id": 402947
        },
        {
            "id": 557236
        },
        {
            "id": 1186329
        }
    ]
}