{
    "id": 128645,
    "name": "CVE-2019-15486",
    "cwe": "CWE-79",
    "modified": "2019-08-26T15:39:54",
    "published": "2019-08-23T11:15:11",
    "status": "Analyzed",
    "summary": "django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_reverse_inline.",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 429092
        },
        {
            "id": 429093
        },
        {
            "id": 429094
        },
        {
            "id": 429095
        },
        {
            "id": 429096
        },
        {
            "id": 429097
        },
        {
            "id": 429098
        },
        {
            "id": 429099
        },
        {
            "id": 429100
        },
        {
            "id": 429101
        },
        {
            "id": 429102
        },
        {
            "id": 429103
        },
        {
            "id": 429104
        },
        {
            "id": 429105
        },
        {
            "id": 429106
        },
        {
            "id": 429107
        },
        {
            "id": 429108
        },
        {
            "id": 429109
        },
        {
            "id": 429110
        },
        {
            "id": 429111
        },
        {
            "id": 429112
        },
        {
            "id": 429113
        },
        {
            "id": 429114
        },
        {
            "id": 429115
        },
        {
            "id": 429116
        },
        {
            "id": 429117
        },
        {
            "id": 429118
        },
        {
            "id": 429119
        }
    ]
}