{
    "id": 197176,
    "name": "CVE-2022-42731",
    "cwe": "CWE-294",
    "modified": "2022-10-11T17:05:57",
    "published": "2022-10-11T12:15:10",
    "status": "Analyzed",
    "summary": "mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.",
    "cvss3": {
        "cvss": 7.5,
        "exploitability_score": 3.9,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
    },
    "cvss2": null,
    "cpes": [
        {
            "id": 943801
        },
        {
            "id": 943802
        },
        {
            "id": 943804
        },
        {
            "id": 943806
        },
        {
            "id": 943807
        },
        {
            "id": 943808
        },
        {
            "id": 943809
        },
        {
            "id": 943810
        },
        {
            "id": 943811
        },
        {
            "id": 943812
        },
        {
            "id": 943813
        },
        {
            "id": 943814
        },
        {
            "id": 943815
        },
        {
            "id": 943816
        },
        {
            "id": 943817
        },
        {
            "id": 943818
        },
        {
            "id": 943819
        },
        {
            "id": 943820
        },
        {
            "id": 943821
        },
        {
            "id": 943822
        },
        {
            "id": 943823
        }
    ]
}