{
    "id": 246706,
    "name": "CVE-2024-32879",
    "cwe": "Unknown",
    "modified": "2024-04-25T11:18:20",
    "published": "2024-04-24T18:15:07",
    "status": "Awaiting Analysis",
    "summary": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
    "cvss3": {
        "cvss": 4.9,
        "exploitability_score": 1.8,
        "impact_score": 2.7,
        "vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:L/I:L/A:N"
    },
    "cvss2": null,
    "cpes": []
}