{
    "id": 71156,
    "name": "CVE-2015-5145",
    "cwe": "CWE-399",
    "modified": "2017-09-21T23:29:23",
    "published": "2015-07-14T15:59:08",
    "status": "Modified",
    "summary": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 100614
        },
        {
            "id": 108168
        },
        {
            "id": 109817
        },
        {
            "id": 127466
        },
        {
            "id": 127467
        },
        {
            "id": 127482
        },
        {
            "id": 127483
        }
    ]
}