{
    "id": 210191,
    "name": "CVE-2023-1436",
    "cwe": "CWE-674",
    "modified": "2023-11-07T03:03:36",
    "published": "2023-03-22T05:15:09",
    "status": "Modified",
    "summary": "An infinite recursion is triggered in Jettison when constructing a JSONArray from a Collection that contains a self-reference in one of its elements. This leads to a StackOverflowError exception being thrown.\n\n",
    "cvss3": {
        "cvss": 7.5,
        "exploitability_score": 3.9,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "cvss2": null,
    "cpes": [
        {
            "id": 983509
        },
        {
            "id": 983510
        },
        {
            "id": 983511
        },
        {
            "id": 983512
        },
        {
            "id": 983513
        },
        {
            "id": 983514
        },
        {
            "id": 983515
        },
        {
            "id": 983516
        },
        {
            "id": 983517
        },
        {
            "id": 983518
        },
        {
            "id": 983519
        },
        {
            "id": 983520
        },
        {
            "id": 983521
        },
        {
            "id": 983522
        },
        {
            "id": 983523
        },
        {
            "id": 983524
        },
        {
            "id": 983525
        },
        {
            "id": 983526
        },
        {
            "id": 983527
        },
        {
            "id": 983528
        },
        {
            "id": 983529
        },
        {
            "id": 983530
        },
        {
            "id": 1194997
        }
    ]
}