{
    "id": 125067,
    "name": "CVE-2019-12903",
    "cwe": "CWE-209",
    "modified": "2021-07-21T09:39:23",
    "published": "2019-06-19T22:15:10",
    "status": "Analyzed",
    "summary": "Pydio Cells before 1.5.0, when supplied with a Name field in an unexpected Unicode format, fails to handle this and includes the database column/table name as pert of the error message, exposing sensitive information.",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 276696
        },
        {
            "id": 276697
        },
        {
            "id": 276698
        },
        {
            "id": 276699
        },
        {
            "id": 276700
        },
        {
            "id": 276701
        },
        {
            "id": 276702
        },
        {
            "id": 276703
        },
        {
            "id": 276704
        },
        {
            "id": 276705
        },
        {
            "id": 276706
        },
        {
            "id": 276707
        },
        {
            "id": 276708
        },
        {
            "id": 276709
        }
    ]
}