{
    "id": 112350,
    "name": "CVE-2018-16438",
    "cwe": "CWE-125",
    "modified": "2018-10-26T13:36:41",
    "published": "2018-09-03T22:29:02",
    "status": "Analyzed",
    "summary": "An issue was discovered in the HDF HDF5 1.8.20 library. There is an out of bounds read in H5L_extern_query at H5Lexternal.c.",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 177554
        }
    ]
}