{
    "id": 256534,
    "name": "CVE-2024-38875",
    "cwe": "Unknown",
    "modified": "2024-07-12T14:11:48",
    "published": "2024-07-10T03:15:12",
    "status": "Awaiting Analysis",
    "summary": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
    "cvss3": {
        "cvss": 7.5,
        "exploitability_score": 3.9,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "cvss2": null,
    "cpes": []
}