{
    "id": 134333,
    "name": "CVE-2019-19588",
    "cwe": "CWE-835",
    "modified": "2020-08-24T15:37:01",
    "published": "2019-12-05T00:15:14",
    "status": "Analyzed",
    "summary": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6.",
    "cvss3": {
        "cvss": 7.5,
        "exploitability_score": 3.9,
        "impact_score": 3.6,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    },
    "cvss2": {
        "exploitability_score": 10.0,
        "impact_score": 6.9,
        "cvss": 7.8,
        "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:C"
    },
    "cpes": [
        {
            "id": 450511
        },
        {
            "id": 450512
        },
        {
            "id": 450513
        },
        {
            "id": 450514
        }
    ]
}