{
    "id": 82987,
    "name": "CVE-2017-6301",
    "cwe": "CWE-125",
    "modified": "2023-11-07T01:49:53",
    "published": "2017-02-24T03:59:00",
    "status": "Modified",
    "summary": "An issue was discovered in ytnef before 1.9.1. This is related to a patch described as \"4 of 9. Out of Bounds Reads.\"",
    "cvss3": null,
    "cvss2": null,
    "cpes": [
        {
            "id": 109409
        },
        {
            "id": 124875
        },
        {
            "id": 403681
        },
        {
            "id": 403682
        },
        {
            "id": 403683
        }
    ]
}